### ISSUE TITLE
semantic similarity results of annotations of msrvtt10k

### ISSUE THREAD

**Issue by JewelChen2019** [mwray/Semantic-Video-Retrieval#1]
hi~ Michael, if possible, could you please share the  similarity results(Bow，Poss,SYN,Meteor) of annotations of msrvtt10k with me?

**Comment by mwray** [comment]
Hi, thanks for your interest in the work, using the code now available you should be able to generate the similarity matrix. Otherwise the MSR-VTT results can be found in the paper: https://mwray.github.io/SSVR/SSVR.pdf
