### ISSUE TITLE
multiple captions per video

### ISSUE THREAD

**Issue by LiJiaBei-7** [mwray/Semantic-Video-Retrieval#4]
I would like to ask how the score is handled for a video with multiple subtitles

**Comment by mwray** [comment]
In the datasets that we tested we didn't have subtitles per video, but if this is the case then I can imagine you can treat the dataset in a similar way to MSR-VTT in which there are multiple captions that are considered relevant for a trimmed video clip.

Hopefully this answers your Q and sorry for the delay!
